apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - image: {{ .Values.deployment.image.name }}:{{ .Values.deployment.image.version }}
        name: {{ .Values.name }}
        ports:
        - containerPort: {{ .Values.deployment.containerport }}
